# Generated by Django 4.1.6 on 2023-02-09 09:35

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Album",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_album", models.CharField(max_length=30)),
                (
                    "date_update",
                    models.DateTimeField(
                        default=datetime.datetime(2023, 2, 9, 16, 35, 13, 392449)
                    ),
                ),
                ("status_delete", models.BooleanField(default=False)),
                (
                    "create_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="count",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CountShort", models.CharField(max_length=40)),
                (
                    "DateURL",
                    models.DateTimeField(
                        default=datetime.datetime(2023, 2, 9, 16, 35, 13, 394449)
                    ),
                ),
                ("Countqr", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_link", models.URLField()),
                ("shortened_link", models.URLField(blank=True, null=True)),
                ("number_random", models.CharField(max_length=20)),
                (
                    "date_now",
                    models.DateTimeField(
                        default=datetime.datetime(2023, 2, 9, 16, 35, 13, 393446)
                    ),
                ),
                (
                    "date_update",
                    models.DateTimeField(
                        default=datetime.datetime(2023, 2, 9, 16, 35, 13, 393446)
                    ),
                ),
                ("check_date", models.BooleanField(default=False)),
                ("ex_date", models.DateTimeField()),
                ("name_album", models.IntegerField()),
                ("key", models.CharField(max_length=20)),
                ("code", models.ImageField(blank=True, upload_to="code")),
                ("status_delete", models.BooleanField(default=False)),
                ("name_qr", models.CharField(max_length=20)),
                (
                    "create_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="log",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("log_error_api_api_path", models.CharField(max_length=50)),
                ("log_error_api_api_error", models.CharField(max_length=50)),
                ("log_error_api_client_device", models.CharField(max_length=50)),
                ("log_error_api_client_data", models.CharField(max_length=50)),
                ("log_error_api_method", models.CharField(max_length=50)),
                ("log_error_api_datenow", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="OfficeUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Story",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("namepath", models.CharField(max_length=20)),
                ("data", models.CharField(max_length=20)),
                ("date", models.DateTimeField()),
                (
                    "create_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "short_url_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Link_Story",
                        to="app.link",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="test",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("code", models.ImageField(upload_to="", verbose_name="images/")),
            ],
        ),
        migrations.DeleteModel(name="Departments",),
        migrations.DeleteModel(name="Employees",),
        migrations.AddField(
            model_name="count",
            name="Link_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Link",
                to="app.link",
            ),
        ),
    ]
